set pages 100
set lines 200

column used_mem_pct format 9999999990

alter session set current_schema=ORAODRMGR;

spool pp

prompt
prompt TOTAL AVAILABLE ORACLE RAC CLUSTERS FOR YOUR DB
prompt

select count(*) total_clusters from PLC_CLUSTERS;

select
prod_or_non_prod,
count(*) cluster_count from PLC_CLUSTERS
group by prod_or_non_prod;


prompt
prompt CHOSEN ORACLE RAC CLUSTERS FOR YOUR DB
prompt     based on available server memory
prompt

SELECT
E.CLUSTER_NAME, A.SCHEMA_NAME,
round((C.MEMORY_AVERAGE_30DAY + ((A.SGA_COMPUTED + A.PGA_COMPUTED) * 100 / F.MEMORY_GB)) ) used_mem_pct,
round((B.CPU_AVERAGE_90DAY + (A.CPU_CORE_COMPUTED * 100 / F.CPU_CORE_COUNT)))
--
FROM
PLC_INTAKE_APP_PROFILES A,
PLC_CLUSTER_CPU_SUM B,
PLC_CLUSTER_MEMORY_SUM C,
--PLC_CLUSTER_LIMITS D,
PLC_CLUSTERS E,
PLC_CLUSTER_CONFIG_SUM F
--,PLC_CLUSTER_LICENSES G
WHERE
A.SCHEMA_NAME='TCOM1' AND
B.CLUSTER_NAME=C.CLUSTER_NAME AND
E.CLUSTER_NAME=B.CLUSTER_NAME AND
F.CLUSTER_NAME=B.CLUSTER_NAME
--G.PARTITIONING_LICENSE_YN = A.PARTITIONING_NEEDED_YN
AND (C.MEMORY_AVERAGE_30DAY + ((A.SGA_COMPUTED + A.PGA_COMPUTED) * 100 / F.MEMORY_GB)) <= 65
AND E.PROD_OR_NON_PROD = DECODE(A.SCHEMA_PURPOSE, 'Prod', 'Prod', 'Non Prod')
AND (B.CPU_AVERAGE_90DAY + (A.CPU_CORE_COMPUTED * 100 / F.CPU_CORE_COUNT)) <= 30
--AND upper(F.CLUSTER_NAME) = g.cluster_name AND G.PARTITIONING_LICENSE_YN = 'Y'
ORDER BY
3 desc
;


/*
--
--(C.MEMORY_AVERAGE_30DAY + ((A.SGA_COMPUTED + A.PGA_COMPUTED) * 100 / F.MEMORY_GB)) <= D.MEMORY_LOAD_LIMIT_AVERAGE
--AND (B.CPU_AVERAGE_90DAY + (A.CPU_CORE_COMPUTED * 100 / F.CPU_CORE_COUNT)) <= D.CPU_LOAD_LIMIT_AVERAGE
--AND
E.PROD_OR_NON_PROD = DECODE(A.SCHEMA_PURPOSE, 'Prod', 'Prod', 'Non Prod')
AND G.PARTITIONING_LICENSE_YN = 'N'
AND A.APP_NAME='T.com customizations'
AND A.SCHEMA_NAME='TCOM1'
--AND G.PARTITIONING_LICENSE_YN = A.PARTITIONING_NEEDED_YN
--AND G.OEM_DATA_MASKING_LICENSE_YN = A.DATA_MASKING_SOURCE_YN
--AND A.PDB_LICENSE_YN = B.PDB_YN
--AND A.ACTIVE_DATAGUARD_LICENSE_YN = B.ACTIVE_DATAGUARD_NEEDED_YN
*/

spool off
