--
-- NOTE - TRY DOING A COMBINED SQL
--

spool placethedb

alter session set current_schema=ORAODRMGR;

SELECT
E.CLUSTER_NAME
FROM
PLC_INTAKE_APP_PROFILES A,
PLC_CLUSTER_CPU_SUM B,
PLC_CLUSTER_MEMORY_SUM C,
PLC_CLUSTER_LIMITS D,
PLC_CLUSTERS E,
PLC_CLUSTER_CONFIG_SUM F,
PLC_CLUSTER_LICENSES G
WHERE
(C.MEMORY_AVERAGE_30DAY + ((A.SGA_COMPUTED + A.PGA_COMPUTED) * 100 / F.MEMORY_GB)) <= D.MEMORY_LOAD_LIMIT_AVERAGE
AND (B.CPU_AVERAGE_90DAY + (A.CPU_CORE_COMPUTED * 100 / F.CPU_CORE_COUNT)) <= D.CPU_LOAD_LIMIT_AVERAGE
AND E.PROD_OR_NON_PROD = DECODE(A.SCHEMA_PURPOSE, 'Prod', 'Prod', 'Non Prod')
AND G.PARTITIONING_LICENSE_YN = 'N'
AND A.APP_NAME='T.com customizations'
AND A.SCHEMA_NAME='TCOM1'
AND A.SCHEMA_PURPOSE='Dev'
--AND G.PARTITIONING_LICENSE_YN = A.PARTITIONING_NEEDED_YN
--AND G.OEM_DATA_MASKING_LICENSE_YN = A.DATA_MASKING_SOURCE_YN
--AND A.PDB_LICENSE_YN = B.PDB_YN
--AND A.ACTIVE_DATAGUARD_LICENSE_YN = B.ACTIVE_DATAGUARD_NEEDED_YN
;

/*
-- Service affinity among cluster nodes
SELECT
A.SERVER_NAME, min(A.CPU_AVERAGE_90DAY)
FROM
PLC_SERVERS A
WHERE
A.CLUSTER_NAME = '&&cluster_name'
GROUP BY SERVER_NAME
;

*/

spool off
