insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RACD11', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RACD12', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RACP30', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RACP31', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RACP32', 'Y', 'N', 'Y', 'N', 'N', 'N');

commit;
