-- CREATE TABLE PLC_INTAKE_APP_PROFILES
-- (
-- SCHEMA_NAME                  VARCHAR2(20),
-- SCHEMA_PURPOSE                       VARCHAR2(20),
-- APP_ACRONYM                  VARCHAR2(20),
-- APP_NAME                     VARCHAR2(20),
-- CONCURRENT_USERS             NUMBER,
-- TRANSACTIONS_PER_SEC         NUMBER,
-- LOAD_PROFILE                 VARCHAR2(20),
-- IOPS_MAX                     NUMBER,
-- STORAGE_NEED_INITIAL_GB              NUMBER,
-- STORAGE_NEED_5YEAR_GB                NUMBER,
-- ACTIVE_DATAGUARD_NEEDED_YN   CHAR(1),
-- PARTITIONING_NEEDED_YN               CHAR(1),
-- DATA_MASKING_SOURCE_YN               CHAR(1),
-- PDB_YN                               CHAR(1),
-- COEXIST_NEEDED_WITH_APP              VARCHAR2(20),
-- PREFERRED_EXISTING_DB                VARCHAR2(20),
-- PREFERRED_EXISTING_CLUSTER   VARCHAR2(20),
-- PREFERRED_REASON_FOR         VARCHAR2(200),
-- IOPS_COMPUTED                        NUMBER,
-- SGA_COMPUTED                 NUMBER,
-- PGA_COMPUTED                 NUMBER,
-- MEMORY_COMPUTED                      NUMBER,
-- CPU_CORE_COMPUTED            NUMBER,
-- FLOPS_COMPUTED               NUMBER
--  );
insert into PLC_INTAKE_APP_PROFILES values
(
'TC1',
'Dev',
'TCM',
'TC customizations',
500,
100,
'OLTP',
200,
20,
200,
'N',
'Y',
'N',
'N',
null,
null,
null,
null,
300,
6,
1,
0,
2,
null
);

insert into PLC_INTAKE_APP_PROFILES values
(
'FT1',
'Dev',
'TCM',
'FT new store',
200,
100,
'OLTP',
200,
20,
200,
'N',
'Y',
'N',
'N',
null,
null,
null,
null,
200,
4,
1,
0,
2,
null
);

commit;
