insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RCLD11', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RCLD12', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RCLP30', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RCLP31', 'Y', 'N', 'Y', 'N', 'N', 'N');
insert into plc_cluster_licenses (cluster_name, PARTITIONING_LICENSE_YN, ACTIVE_DATAGUARD_LICENSE_YN, OEM_DATA_MASKING_LICENSE_YN, PDB_LICENSE_YN, OEM_CLOUD_PACK_LICENSE_YN, OEM_LCM_PACK_LICENSE_YN) values ('RCLP32', 'Y', 'N', 'Y', 'N', 'N', 'N');

commit;
